### ISSUE TITLE
[BUG] Image scaling is abnormal

### ISSUE THREAD

**Issue by wang2956** [raspberrypi/picamera2#167] opened 2022-06-09 16:07 UTC
The runing:
self.picam2 = picamera2.Picamera2()
self.picam2.configure(self.picam2.preview_configuration({"size": (1536, 896)}))
self.picam2.start_preview(Preview.NULL)
self.picam2.start()
....
frame = self._webcam.picam2.capture_array()
if frame is None:
    return
frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
cv2.imshow("Camera", frame)

Both are multiples of 64 (1536, 896)
Then the final image gets only the reduced part.. not all full screen

**Comment by davidplowman** [comment] 2022-06-09 16:15
Hi, thanks for the question. Could you say what kind of Pi and what kind of camera you are using?

If you were able to supply a standalone short script that I could run directly, that would be very helpful. Please also include the code within code tags (triple backquotes) so that the formatting does not get destroyed. Thank you!

**Comment by davidplowman** [comment] 2022-06-10 09:56
Thanks for posting the updated script. It runs fine for me but I'm not quite sure what you mean by "abnormally scaled". Are you referring to the fact that the image is cropped and that you do not see the full field of view of the camera?

The v2 camera supports several different readout modes at different resolutions, and if we don't tell it then it will "guess" which one to use. You can find out the available modes by typing `libcamera-hello --list-cameras`. In this case, it's choosing a 1920x1080 mode because it is larger than the requested size and it has the correct aspect ratio. However, because it needs to use the full sensor resolution it means that it has to crop all the edges off.

In your case, you could replace the `self.picam2.configure(self.picam2.preview_configuration({"size": (1536, 896)}))` line by
```
        config = self.picam2.preview_configuration({"size": (1536, 896)}, raw={"size": (1640, 1232)})
        self.picam2.configure(config)
```
Here, specifying a "raw" stream forces the camera into the 2x2 full field of view binning mode (I took these numbers from the output of `libcamera-hello --list-cameras`). Of course, it still has to crop off the top and bottom because of the aspect ratio, but you should see the full width.

Am I answering the right question? Thanks!

**Comment by davidplowman** [comment] 2022-06-13 10:08
> ...
> Are you referring to the fact that the image is cropped and that you do not see the full field of view of the camera? Yes!!
> 
> ```
>         config = self.picam2.preview_configuration({"size": (1536, 896)}, raw={"size": (1640, 1232)})
>         self.picam2.configure(config)
> ```
> 
> I have set it but it still doesn't show full screen, `libcamera-hello --list-cameras` <- There is display 1920 x 1080. Assuming that 1920 x 1080 is set, only the 200 x 100 part can be seen. Is it possible that the crop is abnormal? or Is there a way to reset the screen?

Hi again, I'm still not really exactly understanding what you've tried and what result you have got. Can you just confirm:

- What image size do you want?
- What preview configuration did you ask for?
- What values does `frame.shape` report?
- If you capture an image (e.g. `self.picam2.capture_file("test.jpg")`) does that have the resolution and field of view that you expect?

Thanks!

**Comment by rarestg** [comment] 2022-08-01 22:30
Hey folks, maybe I can chime in on this. Seeing the same issue on my end. Perhaps I'm misunderstanding the documentation.

Here's the gist of the code I'm using:
```python
def captures():
    resolutions = [(640, 480), (3200, 2400), (3280, 2464)]
    for res in resolutions:
        width, height = res[0], res[1]
        camera = Picamera2()
        camera.configure(camera.create_still_configuration(main={"size": res}))
        camera.capture_file(f"picture_{width}x{height}.jpg")
```

I expected this to output the full image as captured by the sensor, but scaled to the given resolution.
Instead, it actually takes a photo of a crop around the middle of the image sensor!

Here are the photos:
(640, 480)
![img_108_c2_640_480](https://user-images.githubusercontent.com/9878259/182256081-a23b76bf-b9e2-456a-9769-7070c3c9a54e.jpg)

(3200, 2400)
![img_108_c2_3200_2400](https://user-images.githubusercontent.com/9878259/182256096-9ea933b6-bb33-42be-b148-2462cf995403.jpg)

(3280, 2464)
![img_108_c2_3280_2464](https://user-images.githubusercontent.com/9878259/182256103-d0fc99a7-f960-4529-a51d-bc0a0e03bcb2.jpg)

And here are the crop areas, outlined in red:
(640, 480) inside of (3280, 2464)
![640x480_in_2464x3280](https://user-images.githubusercontent.com/9878259/182256130-e1db8be3-16ba-4503-980c-44b240966dd7.jpg)

(3200, 2400) inside of (3280, 2464)
![3200x2400_in_2464x3280](https://user-images.githubusercontent.com/9878259/182256182-37061013-268f-46b8-9d44-9e3685bc2ff4.jpg)

What is the recommended approach to taking a full image with the camera (no cropping!) and simply getting back a low-resolution version. I know I can simply use `cv2.resize()` but I think there's a faster, camera-hardware-based version of accomplishing this, no?

**Comment by davidplowman** [comment] 2022-08-02 10:05
Hi, the problem is that when you specify only the output resolution, the camera doesn't know what sensor mode you really want. You might want the full field of view, or you might want a reduced field of view if that gives you a faster framerate (for example).

For the v2 camera I would recommend either:
```
        camera.configure(camera.create_still_configuration(main={"size": res}, raw={"size": (1640, 1232)}))
```
or
```
        camera.configure(camera.create_still_configuration(main={"size": res}, raw={"size": (3280, 2464)}))
```
The former will give you a faster framerate but lower quality (because the sensor is only outputting 1640x1232). The latter will give you better quality (the sensor is outputting its full resolution) but a slower framerate.

Running `libcamera-hello --list-cameras` will list the available raw sensor resolutions.

The next release of _Picamera2_ will also support listing all the sensor modes, and will even tell you what framerate and field of view they all support.

**Comment by davidplowman** [comment] 2022-08-17 13:12
Hi, is there still anything we can help you with here? If there is please let us know, otherwise I'll consider closing this issue shortly.

**Comment by davidplowman** [comment] 2022-09-05 08:43
Hi again, I think I'll close this issue for the time being. If anything else comes up, or there's anything else for us to look at, please feel free to open a new issue. Thanks!

**Closed by davidplowman** 2022-09-05 08:43 UTC
